package classroom.festivaldatabase;

// Generated 18-mrt-2008 12:18:58 by Hibernate Tools 3.2.0.CR1

import java.util.Date;

/**
 * FestivalScreeningId generated by hbm2java
 */
public class FestivalScreeningId implements java.io.Serializable {

	private Date day;
	private Date time;
	private String place;

	public FestivalScreeningId() {
	}

	public FestivalScreeningId(Date day, Date time, String place) {
		this.day = day;
		this.time = time;
		this.place = place;
	}

	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FestivalScreeningId))
			return false;
		FestivalScreeningId castOther = (FestivalScreeningId) other;

		return ((this.getDay() == castOther.getDay()) || (this.getDay() != null
				&& castOther.getDay() != null && this.getDay().equals(
				castOther.getDay())))
				&& ((this.getTime() == castOther.getTime()) || (this.getTime() != null
						&& castOther.getTime() != null && this.getTime()
						.equals(castOther.getTime())))
				&& ((this.getPlace() == castOther.getPlace()) || (this
						.getPlace() != null
						&& castOther.getPlace() != null && this.getPlace()
						.equals(castOther.getPlace())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDay() == null ? 0 : this.getDay().hashCode());
		result = 37 * result
				+ (getTime() == null ? 0 : this.getTime().hashCode());
		result = 37 * result
				+ (getPlace() == null ? 0 : this.getPlace().hashCode());
		return result;
	}

}
