package classroom.festivaldatabase;

// Generated 18-mrt-2008 12:18:58 by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DirectorName generated by hbm2java
 */
public class DirectorName implements java.io.Serializable {

	private int directorId;
	private String name;
	private Set filmTitles = new HashSet(0);

	public DirectorName() {
	}

	public DirectorName(int directorId, String name) {
		this.directorId = directorId;
		this.name = name;
	}

	public DirectorName(int directorId, String name, Set filmTitles) {
		this.directorId = directorId;
		this.name = name;
		this.filmTitles = filmTitles;
	}

	public int getDirectorId() {
		return this.directorId;
	}

	public void setDirectorId(int directorId) {
		this.directorId = directorId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getFilmTitles() {
		return this.filmTitles;
	}

	public void setFilmTitles(Set filmTitles) {
		this.filmTitles = filmTitles;
	}

}
