package classroom.festivaldatabase;

// Generated 18-mrt-2008 12:18:58 by Hibernate Tools 3.2.0.CR1

/**
 * FestivalEntry generated by hbm2java
 */
public class FestivalEntry implements java.io.Serializable {

	private FestivalEntryId id;
	private FilmTitle filmTitle;
	private FilmCategory filmCategory;
	private int explorezone;

	public FestivalEntry() {
	}

	public FestivalEntry(FestivalEntryId id, FilmTitle filmTitle,
			FilmCategory filmCategory, int explorezone) {
		this.id = id;
		this.filmTitle = filmTitle;
		this.filmCategory = filmCategory;
		this.explorezone = explorezone;
	}

	public FestivalEntryId getId() {
		return this.id;
	}

	public void setId(FestivalEntryId id) {
		this.id = id;
	}

	public FilmTitle getFilmTitle() {
		return this.filmTitle;
	}

	public void setFilmTitle(FilmTitle filmTitle) {
		this.filmTitle = filmTitle;
	}

	public FilmCategory getFilmCategory() {
		return this.filmCategory;
	}

	public void setFilmCategory(FilmCategory filmCategory) {
		this.filmCategory = filmCategory;
	}

	public int getExplorezone() {
		return this.explorezone;
	}

	public void setExplorezone(int explorezone) {
		this.explorezone = explorezone;
	}

}
