package classroom.festivaldatabase;

// Generated 18-mrt-2008 12:18:58 by Hibernate Tools 3.2.0.CR1

/**
 * FestivalEntryId generated by hbm2java
 */
public class FestivalEntryId implements java.io.Serializable {

	private int filmId;
	private int year;

	public FestivalEntryId() {
	}

	public FestivalEntryId(int filmId, int year) {
		this.filmId = filmId;
		this.year = year;
	}

	public int getFilmId() {
		return this.filmId;
	}

	public void setFilmId(int filmId) {
		this.filmId = filmId;
	}

	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FestivalEntryId))
			return false;
		FestivalEntryId castOther = (FestivalEntryId) other;

		return (this.getFilmId() == castOther.getFilmId())
				&& (this.getYear() == castOther.getYear());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFilmId();
		result = 37 * result + this.getYear();
		return result;
	}

}
