package classroom.festivaldatabase;

// Generated 18-mrt-2008 12:18:58 by Hibernate Tools 3.2.0.CR1

/**
 * FestivalScreening generated by hbm2java
 */
public class FestivalScreening implements java.io.Serializable {

	private FestivalScreeningId id;
	private FilmTitle filmTitle;
	private int press;
	private int shortfilm;

	public FestivalScreening() {
	}

	public FestivalScreening(FestivalScreeningId id, FilmTitle filmTitle,
			int press, int shortfilm) {
		this.id = id;
		this.filmTitle = filmTitle;
		this.press = press;
		this.shortfilm = shortfilm;
	}

	public FestivalScreeningId getId() {
		return this.id;
	}

	public void setId(FestivalScreeningId id) {
		this.id = id;
	}

	public FilmTitle getFilmTitle() {
		return this.filmTitle;
	}

	public void setFilmTitle(FilmTitle filmTitle) {
		this.filmTitle = filmTitle;
	}

	public int getPress() {
		return this.press;
	}

	public void setPress(int press) {
		this.press = press;
	}

	public int getShortfilm() {
		return this.shortfilm;
	}

	public void setShortfilm(int shortfilm) {
		this.shortfilm = shortfilm;
	}

}
