package classroom.festivaldatabase;

// Generated 18-mrt-2008 12:18:58 by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * FilmCategory generated by hbm2java
 */
public class FilmCategory implements java.io.Serializable {

	private int categoryId;
	private String name;
	private String keyword;
	private Set festivalEntries = new HashSet(0);

	public FilmCategory() {
	}

	public FilmCategory(int categoryId, String keyword) {
		this.categoryId = categoryId;
		this.keyword = keyword;
	}

	public FilmCategory(int categoryId, String name, String keyword,
			Set festivalEntries) {
		this.categoryId = categoryId;
		this.name = name;
		this.keyword = keyword;
		this.festivalEntries = festivalEntries;
	}

	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public Set getFestivalEntries() {
		return this.festivalEntries;
	}

	public void setFestivalEntries(Set festivalEntries) {
		this.festivalEntries = festivalEntries;
	}

}
