/* $Id$
 * $Name$
 *
 * Copyright 2007 by Howard Shank (hgshank@yahoo.com)
 *
 * The contents of this file are subject to the Mozilla Public License Version 1.1
 * (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the License.
 *
 * The Original Code is 'iText, a free JAVA-PDF library'.
 *
 * The Initial Developer of the Original Code is Bruno Lowagie. Portions created by
 * the Initial Developer are Copyright (C) 1999-2006 by Bruno Lowagie.
 * All Rights Reserved.
 * Co-Developer of the code is Paulo Soares. Portions created by the Co-Developer
 * are Copyright (C) 2000-2006 by Paulo Soares. All Rights Reserved.
 *
 * Contributor(s): all the names of the contributors are added in the source code
 * where applicable.
 *
 * Alternatively, the contents of this file may be used under the terms of the
 * LGPL license (the ?GNU LIBRARY GENERAL PUBLIC LICENSE?), in which case the
 * provisions of LGPL are applicable instead of those above.  If you wish to
 * allow use of your version of this file only under the terms of the LGPL
 * License and not to allow others to use your version of this file under
 * the MPL, indicate your decision by deleting the provisions above and
 * replace them with the notice and other provisions required by the LGPL.
 * If you do not delete the provisions above, a recipient may use your version
 * of this file under either the MPL or the GNU LIBRARY GENERAL PUBLIC LICENSE.
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the MPL as stated above or under the terms of the GNU
 * Library General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Library general Public License for more
 * details.
 *
 * If you didn't download this code from the following link, you should check if
 * you aren't using an obsolete version:
 * http://www.lowagie.com/iText/
 */

package com.lowagie.text.rtf.direct.ctrlwords.basectrlwords;

/* *** WARNING ***************** WARNING ************ WARNING ******
 ********************************************************************
 * This file is automatically generated and should not be modified. *
 * any modification of this file may be overwritten if regenerated. *
 *******************************************************************/

import com.lowagie.text.rtf.direct.RtfParser;
import com.lowagie.text.rtf.direct.ctrlwords.RtfCtrlWordBase;
import com.lowagie.text.rtf.direct.ctrlwords.RtfCtrlWordPropertyType;
import com.lowagie.text.rtf.direct.ctrlwords.RtfCtrlWordType;

/**
 * Description:
 * 	," This control word specifies whether this style shall be
 * 	hidden from the main user interface until it is used.
 * 	If
 * 	this control word?s parameter is ?1?, then this style may be
 * 	used to format content (that is any content which references
 * 	this style shall have its properties as normal), but the
 * 	style shall be hidden from the main user interface
 * 	associated with that application.
 * 	Note   The
 * 	interpretation of a main user interface shall not be
 * 	dictated by this spec, and may be defined by an application
 * 	as appropriate. This setting is intended to define a style
 * 	property that allows styles to be seen and modified in an
 * 	advanced user interface, without exposing the style in a
 * 	less advanced setting. For example, the style that is used
 * 	to format the contents of a comment should typically not be
 * 	shown in a simple user interface, as it is uncommon to want
 * 	to modify it.
 * 	If this control word is omitted or has a
 * 	parameter of ?0?, then the style shall not be required to be
 * 	hidden from the main user interface.
 * Group:
 * 	Style Sheet
 * Type:
 * 	Flag
 * Default Param:
 * 	0
 * Pass Default:
 * 	true
 * RTF Version:
 * 	
 */

public class RtfCtrlWordBase_sunhideused extends RtfCtrlWordBase {

	public RtfCtrlWordBase_sunhideused(RtfParser rtfParser){
		super(rtfParser, "sunhideused", 0, true, RtfCtrlWordType.FLAG, RtfCtrlWordPropertyType.UNIDENTIFIED);
	}
}
