/* Generated By:JavaCC: Do not edit this line. PAParserConstants.java */
package com.lowagie.text.pdf.codec.postscript;

public interface PAParserConstants {

  int EOF = 0;
  int WHITESPACE = 1;
  int INTEGER_LITERAL = 5;
  int DECIMAL_LITERAL = 6;
  int HEX_LITERAL = 7;
  int FLOATING_POINT_LITERAL = 8;
  int EXPONENT = 9;
  int STRING_LITERAL = 10;
  int IDENTIFIER = 11;
  int KEY_IDENTIFIER = 12;
  int IMMEDIATE_IDENTIFIER = 13;
  int LETTER = 14;
  int DIGIT = 15;
  int LBRACE = 16;
  int RBRACE = 17;
  int LBRACKET = 18;
  int RBRACKET = 19;
  int LDICT = 20;
  int RDICT = 21;
  int Nextchar = 22;
  int HEX_STRING_LITERAL = 23;
  int Instring = 24;

  int DEFAULT = 0;
  int WITHINSTRING = 1;

  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<token of kind 2>",
    "<token of kind 3>",
    "<token of kind 4>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<KEY_IDENTIFIER>",
    "<IMMEDIATE_IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"<<\"",
    "\">>\"",
    "<Nextchar>",
    "\">\"",
    "\"<\"",
  };

}
