/*
 * $Id$
 * $Name$
 *
 * Data: Copyright 1985-... Adobe Systems Incorporated.  All Rights Reserved.
 * Java: Copyright 2001 Paulo Soares
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or any
 * later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Library general Public License for more
 * details.
 *
 * You should have received a copy of the GNU Library General Public License along
 * with this library; if not, write to the Free Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 *
 * If you didn't download this code from the following link, you should check if
 * you aren't using an obsolete version:
 * http://www.lowagie.com/iText/
 *
 * ir-arch Bruno Lowagie,
 * Adolf Baeyensstraat 121
 * 9040 Sint-Amandsberg
 * BELGIUM
 * tel. +32 (0)9 228.10.97
 * bruno@lowagie.com
 *
 */

package com.lowagie.text.pdf.afm;

public class TimesItalic2
{
    public static String afm =
    "KPX R Omacron -40\n"+
    "KPX R Oslash -40\n"+
    "KPX R Otilde -40\n"+
    "KPX R U -40\n"+
    "KPX R Uacute -40\n"+
    "KPX R Ucircumflex -40\n"+
    "KPX R Udieresis -40\n"+
    "KPX R Ugrave -40\n"+
    "KPX R Uhungarumlaut -40\n"+
    "KPX R Umacron -40\n"+
    "KPX R Uogonek -40\n"+
    "KPX R Uring -40\n"+
    "KPX R V -18\n"+
    "KPX R W -18\n"+
    "KPX R Y -18\n"+
    "KPX R Yacute -18\n"+
    "KPX R Ydieresis -18\n"+
    "KPX Racute O -40\n"+
    "KPX Racute Oacute -40\n"+
    "KPX Racute Ocircumflex -40\n"+
    "KPX Racute Odieresis -40\n"+
    "KPX Racute Ograve -40\n"+
    "KPX Racute Ohungarumlaut -40\n"+
    "KPX Racute Omacron -40\n"+
    "KPX Racute Oslash -40\n"+
    "KPX Racute Otilde -40\n"+
    "KPX Racute U -40\n"+
    "KPX Racute Uacute -40\n"+
    "KPX Racute Ucircumflex -40\n"+
    "KPX Racute Udieresis -40\n"+
    "KPX Racute Ugrave -40\n"+
    "KPX Racute Uhungarumlaut -40\n"+
    "KPX Racute Umacron -40\n"+
    "KPX Racute Uogonek -40\n"+
    "KPX Racute Uring -40\n"+
    "KPX Racute V -18\n"+
    "KPX Racute W -18\n"+
    "KPX Racute Y -18\n"+
    "KPX Racute Yacute -18\n"+
    "KPX Racute Ydieresis -18\n"+
    "KPX Rcaron O -40\n"+
    "KPX Rcaron Oacute -40\n"+
    "KPX Rcaron Ocircumflex -40\n"+
    "KPX Rcaron Odieresis -40\n"+
    "KPX Rcaron Ograve -40\n"+
    "KPX Rcaron Ohungarumlaut -40\n"+
    "KPX Rcaron Omacron -40\n"+
    "KPX Rcaron Oslash -40\n"+
    "KPX Rcaron Otilde -40\n"+
    "KPX Rcaron U -40\n"+
    "KPX Rcaron Uacute -40\n"+
    "KPX Rcaron Ucircumflex -40\n"+
    "KPX Rcaron Udieresis -40\n"+
    "KPX Rcaron Ugrave -40\n"+
    "KPX Rcaron Uhungarumlaut -40\n"+
    "KPX Rcaron Umacron -40\n"+
    "KPX Rcaron Uogonek -40\n"+
    "KPX Rcaron Uring -40\n"+
    "KPX Rcaron V -18\n"+
    "KPX Rcaron W -18\n"+
    "KPX Rcaron Y -18\n"+
    "KPX Rcaron Yacute -18\n"+
    "KPX Rcaron Ydieresis -18\n"+
    "KPX Rcommaaccent O -40\n"+
    "KPX Rcommaaccent Oacute -40\n"+
    "KPX Rcommaaccent Ocircumflex -40\n"+
    "KPX Rcommaaccent Odieresis -40\n"+
    "KPX Rcommaaccent Ograve -40\n"+
    "KPX Rcommaaccent Ohungarumlaut -40\n"+
    "KPX Rcommaaccent Omacron -40\n"+
    "KPX Rcommaaccent Oslash -40\n"+
    "KPX Rcommaaccent Otilde -40\n"+
    "KPX Rcommaaccent U -40\n"+
    "KPX Rcommaaccent Uacute -40\n"+
    "KPX Rcommaaccent Ucircumflex -40\n"+
    "KPX Rcommaaccent Udieresis -40\n"+
    "KPX Rcommaaccent Ugrave -40\n"+
    "KPX Rcommaaccent Uhungarumlaut -40\n"+
    "KPX Rcommaaccent Umacron -40\n"+
    "KPX Rcommaaccent Uogonek -40\n"+
    "KPX Rcommaaccent Uring -40\n"+
    "KPX Rcommaaccent V -18\n"+
    "KPX Rcommaaccent W -18\n"+
    "KPX Rcommaaccent Y -18\n"+
    "KPX Rcommaaccent Yacute -18\n"+
    "KPX Rcommaaccent Ydieresis -18\n"+
    "KPX T A -50\n"+
    "KPX T Aacute -50\n"+
    "KPX T Abreve -50\n"+
    "KPX T Acircumflex -50\n"+
    "KPX T Adieresis -50\n"+
    "KPX T Agrave -50\n"+
    "KPX T Amacron -50\n"+
    "KPX T Aogonek -50\n"+
    "KPX T Aring -50\n"+
    "KPX T Atilde -50\n"+
    "KPX T O -18\n"+
    "KPX T Oacute -18\n"+
    "KPX T Ocircumflex -18\n"+
    "KPX T Odieresis -18\n"+
    "KPX T Ograve -18\n"+
    "KPX T Ohungarumlaut -18\n"+
    "KPX T Omacron -18\n"+
    "KPX T Oslash -18\n"+
    "KPX T Otilde -18\n"+
    "KPX T a -92\n"+
    "KPX T aacute -92\n"+
    "KPX T abreve -92\n"+
    "KPX T acircumflex -92\n"+
    "KPX T adieresis -92\n"+
    "KPX T agrave -92\n"+
    "KPX T amacron -92\n"+
    "KPX T aogonek -92\n"+
    "KPX T aring -92\n"+
    "KPX T atilde -92\n"+
    "KPX T colon -55\n"+
    "KPX T comma -74\n"+
    "KPX T e -92\n"+
    "KPX T eacute -92\n"+
    "KPX T ecaron -92\n"+
    "KPX T ecircumflex -52\n"+
    "KPX T edieresis -52\n"+
    "KPX T edotaccent -92\n"+
    "KPX T egrave -52\n"+
    "KPX T emacron -52\n"+
    "KPX T eogonek -92\n"+
    "KPX T hyphen -74\n"+
    "KPX T i -55\n"+
    "KPX T iacute -55\n"+
    "KPX T iogonek -55\n"+
    "KPX T o -92\n"+
    "KPX T oacute -92\n"+
    "KPX T ocircumflex -92\n"+
    "KPX T odieresis -92\n"+
    "KPX T ograve -92\n"+
    "KPX T ohungarumlaut -92\n"+
    "KPX T omacron -92\n"+
    "KPX T oslash -92\n"+
    "KPX T otilde -92\n"+
    "KPX T period -74\n"+
    "KPX T r -55\n"+
    "KPX T racute -55\n"+
    "KPX T rcaron -55\n"+
    "KPX T rcommaaccent -55\n"+
    "KPX T semicolon -65\n"+
    "KPX T u -55\n"+
    "KPX T uacute -55\n"+
    "KPX T ucircumflex -55\n"+
    "KPX T udieresis -55\n"+
    "KPX T ugrave -55\n"+
    "KPX T uhungarumlaut -55\n"+
    "KPX T umacron -55\n"+
    "KPX T uogonek -55\n"+
    "KPX T uring -55\n"+
    "KPX T w -74\n"+
    "KPX T y -74\n"+
    "KPX T yacute -74\n"+
    "KPX T ydieresis -34\n"+
    "KPX Tcaron A -50\n"+
    "KPX Tcaron Aacute -50\n"+
    "KPX Tcaron Abreve -50\n"+
    "KPX Tcaron Acircumflex -50\n"+
    "KPX Tcaron Adieresis -50\n"+
    "KPX Tcaron Agrave -50\n"+
    "KPX Tcaron Amacron -50\n"+
    "KPX Tcaron Aogonek -50\n"+
    "KPX Tcaron Aring -50\n"+
    "KPX Tcaron Atilde -50\n"+
    "KPX Tcaron O -18\n"+
    "KPX Tcaron Oacute -18\n"+
    "KPX Tcaron Ocircumflex -18\n"+
    "KPX Tcaron Odieresis -18\n"+
    "KPX Tcaron Ograve -18\n"+
    "KPX Tcaron Ohungarumlaut -18\n"+
    "KPX Tcaron Omacron -18\n"+
    "KPX Tcaron Oslash -18\n"+
    "KPX Tcaron Otilde -18\n"+
    "KPX Tcaron a -92\n"+
    "KPX Tcaron aacute -92\n"+
    "KPX Tcaron abreve -92\n"+
    "KPX Tcaron acircumflex -92\n"+
    "KPX Tcaron adieresis -92\n"+
    "KPX Tcaron agrave -92\n"+
    "KPX Tcaron amacron -92\n"+
    "KPX Tcaron aogonek -92\n"+
    "KPX Tcaron aring -92\n"+
    "KPX Tcaron atilde -92\n"+
    "KPX Tcaron colon -55\n"+
    "KPX Tcaron comma -74\n"+
    "KPX Tcaron e -92\n"+
    "KPX Tcaron eacute -92\n"+
    "KPX Tcaron ecaron -92\n"+
    "KPX Tcaron ecircumflex -52\n"+
    "KPX Tcaron edieresis -52\n"+
    "KPX Tcaron edotaccent -92\n"+
    "KPX Tcaron egrave -52\n"+
    "KPX Tcaron emacron -52\n"+
    "KPX Tcaron eogonek -92\n"+
    "KPX Tcaron hyphen -74\n"+
    "KPX Tcaron i -55\n"+
    "KPX Tcaron iacute -55\n"+
    "KPX Tcaron iogonek -55\n"+
    "KPX Tcaron o -92\n"+
    "KPX Tcaron oacute -92\n"+
    "KPX Tcaron ocircumflex -92\n"+
    "KPX Tcaron odieresis -92\n"+
    "KPX Tcaron ograve -92\n"+
    "KPX Tcaron ohungarumlaut -92\n"+
    "KPX Tcaron omacron -92\n"+
    "KPX Tcaron oslash -92\n"+
    "KPX Tcaron otilde -92\n"+
    "KPX Tcaron period -74\n"+
    "KPX Tcaron r -55\n"+
    "KPX Tcaron racute -55\n"+
    "KPX Tcaron rcaron -55\n"+
    "KPX Tcaron rcommaaccent -55\n"+
    "KPX Tcaron semicolon -65\n"+
    "KPX Tcaron u -55\n"+
    "KPX Tcaron uacute -55\n"+
    "KPX Tcaron ucircumflex -55\n"+
    "KPX Tcaron udieresis -55\n"+
    "KPX Tcaron ugrave -55\n"+
    "KPX Tcaron uhungarumlaut -55\n"+
    "KPX Tcaron umacron -55\n"+
    "KPX Tcaron uogonek -55\n"+
    "KPX Tcaron uring -55\n"+
    "KPX Tcaron w -74\n"+
    "KPX Tcaron y -74\n"+
    "KPX Tcaron yacute -74\n"+
    "KPX Tcaron ydieresis -34\n"+
    "KPX Tcommaaccent A -50\n"+
    "KPX Tcommaaccent Aacute -50\n"+
    "KPX Tcommaaccent Abreve -50\n"+
    "KPX Tcommaaccent Acircumflex -50\n"+
    "KPX Tcommaaccent Adieresis -50\n"+
    "KPX Tcommaaccent Agrave -50\n"+
    "KPX Tcommaaccent Amacron -50\n"+
    "KPX Tcommaaccent Aogonek -50\n"+
    "KPX Tcommaaccent Aring -50\n"+
    "KPX Tcommaaccent Atilde -50\n"+
    "KPX Tcommaaccent O -18\n"+
    "KPX Tcommaaccent Oacute -18\n"+
    "KPX Tcommaaccent Ocircumflex -18\n"+
    "KPX Tcommaaccent Odieresis -18\n"+
    "KPX Tcommaaccent Ograve -18\n"+
    "KPX Tcommaaccent Ohungarumlaut -18\n"+
    "KPX Tcommaaccent Omacron -18\n"+
    "KPX Tcommaaccent Oslash -18\n"+
    "KPX Tcommaaccent Otilde -18\n"+
    "KPX Tcommaaccent a -92\n"+
    "KPX Tcommaaccent aacute -92\n"+
    "KPX Tcommaaccent abreve -92\n"+
    "KPX Tcommaaccent acircumflex -92\n"+
    "KPX Tcommaaccent adieresis -92\n"+
    "KPX Tcommaaccent agrave -92\n"+
    "KPX Tcommaaccent amacron -92\n"+
    "KPX Tcommaaccent aogonek -92\n"+
    "KPX Tcommaaccent aring -92\n"+
    "KPX Tcommaaccent atilde -92\n"+
    "KPX Tcommaaccent colon -55\n"+
    "KPX Tcommaaccent comma -74\n"+
    "KPX Tcommaaccent e -92\n"+
    "KPX Tcommaaccent eacute -92\n"+
    "KPX Tcommaaccent ecaron -92\n"+
    "KPX Tcommaaccent ecircumflex -52\n"+
    "KPX Tcommaaccent edieresis -52\n"+
    "KPX Tcommaaccent edotaccent -92\n"+
    "KPX Tcommaaccent egrave -52\n"+
    "KPX Tcommaaccent emacron -52\n"+
    "KPX Tcommaaccent eogonek -92\n"+
    "KPX Tcommaaccent hyphen -74\n"+
    "KPX Tcommaaccent i -55\n"+
    "KPX Tcommaaccent iacute -55\n"+
    "KPX Tcommaaccent iogonek -55\n"+
    "KPX Tcommaaccent o -92\n"+
    "KPX Tcommaaccent oacute -92\n"+
    "KPX Tcommaaccent ocircumflex -92\n"+
    "KPX Tcommaaccent odieresis -92\n"+
    "KPX Tcommaaccent ograve -92\n"+
    "KPX Tcommaaccent ohungarumlaut -92\n"+
    "KPX Tcommaaccent omacron -92\n"+
    "KPX Tcommaaccent oslash -92\n"+
    "KPX Tcommaaccent otilde -92\n"+
    "KPX Tcommaaccent period -74\n"+
    "KPX Tcommaaccent r -55\n"+
    "KPX Tcommaaccent racute -55\n"+
    "KPX Tcommaaccent rcaron -55\n"+
    "KPX Tcommaaccent rcommaaccent -55\n"+
    "KPX Tcommaaccent semicolon -65\n"+
    "KPX Tcommaaccent u -55\n"+
    "KPX Tcommaaccent uacute -55\n"+
    "KPX Tcommaaccent ucircumflex -55\n"+
    "KPX Tcommaaccent udieresis -55\n"+
    "KPX Tcommaaccent ugrave -55\n"+
    "KPX Tcommaaccent uhungarumlaut -55\n"+
    "KPX Tcommaaccent umacron -55\n"+
    "KPX Tcommaaccent uogonek -55\n"+
    "KPX Tcommaaccent uring -55\n"+
    "KPX Tcommaaccent w -74\n"+
    "KPX Tcommaaccent y -74\n"+
    "KPX Tcommaaccent yacute -74\n"+
    "KPX Tcommaaccent ydieresis -34\n"+
    "KPX U A -40\n"+
    "KPX U Aacute -40\n"+
    "KPX U Abreve -40\n"+
    "KPX U Acircumflex -40\n"+
    "KPX U Adieresis -40\n"+
    "KPX U Agrave -40\n"+
    "KPX U Amacron -40\n"+
    "KPX U Aogonek -40\n"+
    "KPX U Aring -40\n"+
    "KPX U Atilde -40\n"+
    "KPX U comma -25\n"+
    "KPX U period -25\n"+
    "KPX Uacute A -40\n"+
    "KPX Uacute Aacute -40\n"+
    "KPX Uacute Abreve -40\n"+
    "KPX Uacute Acircumflex -40\n"+
    "KPX Uacute Adieresis -40\n"+
    "KPX Uacute Agrave -40\n"+
    "KPX Uacute Amacron -40\n"+
    "KPX Uacute Aogonek -40\n"+
    "KPX Uacute Aring -40\n"+
    "KPX Uacute Atilde -40\n"+
    "KPX Uacute comma -25\n"+
    "KPX Uacute period -25\n"+
    "KPX Ucircumflex A -40\n"+
    "KPX Ucircumflex Aacute -40\n"+
    "KPX Ucircumflex Abreve -40\n"+
    "KPX Ucircumflex Acircumflex -40\n"+
    "KPX Ucircumflex Adieresis -40\n"+
    "KPX Ucircumflex Agrave -40\n"+
    "KPX Ucircumflex Amacron -40\n"+
    "KPX Ucircumflex Aogonek -40\n"+
    "KPX Ucircumflex Aring -40\n"+
    "KPX Ucircumflex Atilde -40\n"+
    "KPX Ucircumflex comma -25\n"+
    "KPX Ucircumflex period -25\n"+
    "KPX Udieresis A -40\n"+
    "KPX Udieresis Aacute -40\n"+
    "KPX Udieresis Abreve -40\n"+
    "KPX Udieresis Acircumflex -40\n"+
    "KPX Udieresis Adieresis -40\n"+
    "KPX Udieresis Agrave -40\n"+
    "KPX Udieresis Amacron -40\n"+
    "KPX Udieresis Aogonek -40\n"+
    "KPX Udieresis Aring -40\n"+
    "KPX Udieresis Atilde -40\n"+
    "KPX Udieresis comma -25\n"+
    "KPX Udieresis period -25\n"+
    "KPX Ugrave A -40\n"+
    "KPX Ugrave Aacute -40\n"+
    "KPX Ugrave Abreve -40\n"+
    "KPX Ugrave Acircumflex -40\n"+
    "KPX Ugrave Adieresis -40\n"+
    "KPX Ugrave Agrave -40\n"+
    "KPX Ugrave Amacron -40\n"+
    "KPX Ugrave Aogonek -40\n"+
    "KPX Ugrave Aring -40\n"+
    "KPX Ugrave Atilde -40\n"+
    "KPX Ugrave comma -25\n"+
    "KPX Ugrave period -25\n"+
    "KPX Uhungarumlaut A -40\n"+
    "KPX Uhungarumlaut Aacute -40\n"+
    "KPX Uhungarumlaut Abreve -40\n"+
    "KPX Uhungarumlaut Acircumflex -40\n"+
    "KPX Uhungarumlaut Adieresis -40\n"+
    "KPX Uhungarumlaut Agrave -40\n"+
    "KPX Uhungarumlaut Amacron -40\n"+
    "KPX Uhungarumlaut Aogonek -40\n"+
    "KPX Uhungarumlaut Aring -40\n"+
    "KPX Uhungarumlaut Atilde -40\n"+
    "KPX Uhungarumlaut comma -25\n"+
    "KPX Uhungarumlaut period -25\n"+
    "KPX Umacron A -40\n"+
    "KPX Umacron Aacute -40\n"+
    "KPX Umacron Abreve -40\n"+
    "KPX Umacron Acircumflex -40\n"+
    "KPX Umacron Adieresis -40\n"+
    "KPX Umacron Agrave -40\n"+
    "KPX Umacron Amacron -40\n"+
    "KPX Umacron Aogonek -40\n"+
    "KPX Umacron Aring -40\n"+
    "KPX Umacron Atilde -40\n"+
    "KPX Umacron comma -25\n"+
    "KPX Umacron period -25\n"+
    "KPX Uogonek A -40\n"+
    "KPX Uogonek Aacute -40\n"+
    "KPX Uogonek Abreve -40\n"+
    "KPX Uogonek Acircumflex -40\n"+
    "KPX Uogonek Adieresis -40\n"+
    "KPX Uogonek Agrave -40\n"+
    "KPX Uogonek Amacron -40\n"+
    "KPX Uogonek Aogonek -40\n"+
    "KPX Uogonek Aring -40\n"+
    "KPX Uogonek Atilde -40\n"+
    "KPX Uogonek comma -25\n"+
    "KPX Uogonek period -25\n"+
    "KPX Uring A -40\n"+
    "KPX Uring Aacute -40\n"+
    "KPX Uring Abreve -40\n"+
    "KPX Uring Acircumflex -40\n"+
    "KPX Uring Adieresis -40\n"+
    "KPX Uring Agrave -40\n"+
    "KPX Uring Amacron -40\n"+
    "KPX Uring Aogonek -40\n"+
    "KPX Uring Aring -40\n"+
    "KPX Uring Atilde -40\n"+
    "KPX Uring comma -25\n"+
    "KPX Uring period -25\n"+
    "KPX V A -60\n"+
    "KPX V Aacute -60\n"+
    "KPX V Abreve -60\n"+
    "KPX V Acircumflex -60\n"+
    "KPX V Adieresis -60\n"+
    "KPX V Agrave -60\n"+
    "KPX V Amacron -60\n"+
    "KPX V Aogonek -60\n"+
    "KPX V Aring -60\n"+
    "KPX V Atilde -60\n"+
    "KPX V O -30\n"+
    "KPX V Oacute -30\n"+
    "KPX V Ocircumflex -30\n"+
    "KPX V Odieresis -30\n"+
    "KPX V Ograve -30\n"+
    "KPX V Ohungarumlaut -30\n"+
    "KPX V Omacron -30\n"+
    "KPX V Oslash -30\n"+
    "KPX V Otilde -30\n"+
    "KPX V a -111\n"+
    "KPX V aacute -111\n"+
    "KPX V abreve -111\n"+
    "KPX V acircumflex -111\n"+
    "KPX V adieresis -111\n"+
    "KPX V agrave -111\n"+
    "KPX V amacron -111\n"+
    "KPX V aogonek -111\n"+
    "KPX V aring -111\n"+
    "KPX V atilde -111\n"+
    "KPX V colon -65\n"+
    "KPX V comma -129\n"+
    "KPX V e -111\n"+
    "KPX V eacute -111\n"+
    "KPX V ecaron -111\n"+
    "KPX V ecircumflex -111\n"+
    "KPX V edieresis -71\n"+
    "KPX V edotaccent -111\n"+
    "KPX V egrave -71\n"+
    "KPX V emacron -71\n"+
    "KPX V eogonek -111\n"+
    "KPX V hyphen -55\n"+
    "KPX V i -74\n"+
    "KPX V iacute -74\n"+
    "KPX V icircumflex -34\n"+
    "KPX V idieresis -34\n"+
    "KPX V igrave -34\n"+
    "KPX V imacron -34\n"+
    "KPX V iogonek -74\n"+
    "KPX V o -111\n"+
    "KPX V oacute -111\n"+
    "KPX V ocircumflex -111\n"+
    "KPX V odieresis -111\n"+
    "KPX V ograve -111\n"+
    "KPX V ohungarumlaut -111\n"+
    "KPX V omacron -111\n"+
    "KPX V oslash -111\n"+
    "KPX V otilde -111\n"+
    "KPX V period -129\n"+
    "KPX V semicolon -74\n"+
    "KPX V u -74\n"+
    "KPX V uacute -74\n"+
    "KPX V ucircumflex -74\n"+
    "KPX V udieresis -74\n"+
    "KPX V ugrave -74\n"+
    "KPX V uhungarumlaut -74\n"+
    "KPX V umacron -74\n"+
    "KPX V uogonek -74\n"+
    "KPX V uring -74\n"+
    "KPX W A -60\n"+
    "KPX W Aacute -60\n"+
    "KPX W Abreve -60\n"+
    "KPX W Acircumflex -60\n"+
    "KPX W Adieresis -60\n"+
    "KPX W Agrave -60\n"+
    "KPX W Amacron -60\n"+
    "KPX W Aogonek -60\n"+
    "KPX W Aring -60\n"+
    "KPX W Atilde -60\n"+
    "KPX W O -25\n"+
    "KPX W Oacute -25\n"+
    "KPX W Ocircumflex -25\n"+
    "KPX W Odieresis -25\n"+
    "KPX W Ograve -25\n"+
    "KPX W Ohungarumlaut -25\n"+
    "KPX W Omacron -25\n"+
    "KPX W Oslash -25\n"+
    "KPX W Otilde -25\n"+
    "KPX W a -92\n"+
    "KPX W aacute -92\n"+
    "KPX W abreve -92\n"+
    "KPX W acircumflex -92\n"+
    "KPX W adieresis -92\n"+
    "KPX W agrave -92\n"+
    "KPX W amacron -92\n"+
    "KPX W aogonek -92\n"+
    "KPX W aring -92\n"+
    "KPX W atilde -92\n"+
    "KPX W colon -65\n"+
    "KPX W comma -92\n"+
    "KPX W e -92\n"+
    "KPX W eacute -92\n"+
    "KPX W ecaron -92\n"+
    "KPX W ecircumflex -92\n"+
    "KPX W edieresis -52\n"+
    "KPX W edotaccent -92\n"+
    "KPX W egrave -52\n"+
    "KPX W emacron -52\n"+
    "KPX W eogonek -92\n"+
    "KPX W hyphen -37\n"+
    "KPX W i -55\n"+
    "KPX W iacute -55\n"+
    "KPX W iogonek -55\n"+
    "KPX W o -92\n"+
    "KPX W oacute -92\n"+
    "KPX W ocircumflex -92\n"+
    "KPX W odieresis -92\n"+
    "KPX W ograve -92\n"+
    "KPX W ohungarumlaut -92\n"+
    "KPX W omacron -92\n"+
    "KPX W oslash -92\n"+
    "KPX W otilde -92\n"+
    "KPX W period -92\n"+
    "KPX W semicolon -65\n"+
    "KPX W u -55\n"+
    "KPX W uacute -55\n"+
    "KPX W ucircumflex -55\n"+
    "KPX W udieresis -55\n"+
    "KPX W ugrave -55\n"+
    "KPX W uhungarumlaut -55\n"+
    "KPX W umacron -55\n"+
    "KPX W uogonek -55\n"+
    "KPX W uring -55\n"+
    "KPX W y -70\n"+
    "KPX W yacute -70\n"+
    "KPX W ydieresis -70\n"+
    "KPX Y A -50\n"+
    "KPX Y Aacute -50\n"+
    "KPX Y Abreve -50\n"+
    "KPX Y Acircumflex -50\n"+
    "KPX Y Adieresis -50\n"+
    "KPX Y Agrave -50\n"+
    "KPX Y Amacron -50\n"+
    "KPX Y Aogonek -50\n"+
    "KPX Y Aring -50\n"+
    "KPX Y Atilde -50\n"+
    "KPX Y O -15\n"+
    "KPX Y Oacute -15\n"+
    "KPX Y Ocircumflex -15\n"+
    "KPX Y Odieresis -15\n"+
    "KPX Y Ograve -15\n"+
    "KPX Y Ohungarumlaut -15\n"+
    "KPX Y Omacron -15\n"+
    "KPX Y Oslash -15\n"+
    "KPX Y Otilde -15\n"+
    "KPX Y a -92\n"+
    "KPX Y aacute -92\n"+
    "KPX Y abreve -92\n"+
    "KPX Y acircumflex -92\n"+
    "KPX Y adieresis -92\n"+
    "KPX Y agrave -92\n"+
    "KPX Y amacron -92\n"+
    "KPX Y aogonek -92\n"+
    "KPX Y aring -92\n"+
    "KPX Y atilde -92\n"+
    "KPX Y colon -65\n"+
    "KPX Y comma -92\n"+
    "KPX Y e -92\n"+
    "KPX Y eacute -92\n"+
    "KPX Y ecaron -92\n"+
    "KPX Y ecircumflex -92\n"+
    "KPX Y edieresis -52\n"+
    "KPX Y edotaccent -92\n"+
    "KPX Y egrave -52\n"+
    "KPX Y emacron -52\n"+
    "KPX Y eogonek -92\n"+
    "KPX Y hyphen -74\n"+
    "KPX Y i -74\n"+
    "KPX Y iacute -74\n"+
    "KPX Y icircumflex -34\n"+
    "KPX Y idieresis -34\n"+
    "KPX Y igrave -34\n"+
    "KPX Y imacron -34\n"+
    "KPX Y iogonek -74\n"+
    "KPX Y o -92\n"+
    "KPX Y oacute -92\n"+
    "KPX Y ocircumflex -92\n"+
    "KPX Y odieresis -92\n"+
    "KPX Y ograve -92\n"+
    "KPX Y ohungarumlaut -92\n"+
    "KPX Y omacron -92\n"+
    "KPX Y oslash -92\n"+
    "KPX Y otilde -92\n"+
    "KPX Y period -92\n"+
    "KPX Y semicolon -65\n"+
    "KPX Y u -92\n"+
    "KPX Y uacute -92\n"+
    "KPX Y ucircumflex -92\n"+
    "KPX Y udieresis -92\n"+
    "KPX Y ugrave -92\n"+
    "KPX Y uhungarumlaut -92\n"+
    "KPX Y umacron -92\n"+
    "KPX Y uogonek -92\n"+
    "KPX Y uring -92\n"+
    "KPX Yacute A -50\n"+
    "KPX Yacute Aacute -50\n"+
    "KPX Yacute Abreve -50\n"+
    "KPX Yacute Acircumflex -50\n"+
    "KPX Yacute Adieresis -50\n"+
    "KPX Yacute Agrave -50\n"+
    "KPX Yacute Amacron -50\n"+
    "KPX Yacute Aogonek -50\n"+
    "KPX Yacute Aring -50\n"+
    "KPX Yacute Atilde -50\n"+
    "KPX Yacute O -15\n"+
    "KPX Yacute Oacute -15\n"+
    "KPX Yacute Ocircumflex -15\n"+
    "KPX Yacute Odieresis -15\n"+
    "KPX Yacute Ograve -15\n"+
    "KPX Yacute Ohungarumlaut -15\n"+
    "KPX Yacute Omacron -15\n"+
    "KPX Yacute Oslash -15\n"+
    "KPX Yacute Otilde -15\n"+
    "KPX Yacute a -92\n"+
    "KPX Yacute aacute -92\n"+
    "KPX Yacute abreve -92\n"+
    "KPX Yacute acircumflex -92\n"+
    "KPX Yacute adieresis -92\n"+
    "KPX Yacute agrave -92\n"+
    "KPX Yacute amacron -92\n"+
    "KPX Yacute aogonek -92\n"+
    "KPX Yacute aring -92\n"+
    "KPX Yacute atilde -92\n"+
    "KPX Yacute colon -65\n"+
    "KPX Yacute comma -92\n"+
    "KPX Yacute e -92\n"+
    "KPX Yacute eacute -92\n"+
    "KPX Yacute ecaron -92\n"+
    "KPX Yacute ecircumflex -92\n"+
    "KPX Yacute edieresis -52\n"+
    "KPX Yacute edotaccent -92\n"+
    "KPX Yacute egrave -52\n"+
    "KPX Yacute emacron -52\n"+
    "KPX Yacute eogonek -92\n"+
    "KPX Yacute hyphen -74\n"+
    "KPX Yacute i -74\n"+
    "KPX Yacute iacute -74\n"+
    "KPX Yacute icircumflex -34\n"+
    "KPX Yacute idieresis -34\n"+
    "KPX Yacute igrave -34\n"+
    "KPX Yacute imacron -34\n"+
    "KPX Yacute iogonek -74\n"+
    "KPX Yacute o -92\n"+
    "KPX Yacute oacute -92\n"+
    "KPX Yacute ocircumflex -92\n"+
    "KPX Yacute odieresis -92\n"+
    "KPX Yacute ograve -92\n"+
    "KPX Yacute ohungarumlaut -92\n"+
    "KPX Yacute omacron -92\n"+
    "KPX Yacute oslash -92\n"+
    "KPX Yacute otilde -92\n"+
    "KPX Yacute period -92\n"+
    "KPX Yacute semicolon -65\n"+
    "KPX Yacute u -92\n"+
    "KPX Yacute uacute -92\n"+
    "KPX Yacute ucircumflex -92\n"+
    "KPX Yacute udieresis -92\n"+
    "KPX Yacute ugrave -92\n"+
    "KPX Yacute uhungarumlaut -92\n"+
    "KPX Yacute umacron -92\n"+
    "KPX Yacute uogonek -92\n"+
    "KPX Yacute uring -92\n"+
    "KPX Ydieresis A -50\n"+
    "KPX Ydieresis Aacute -50\n"+
    "KPX Ydieresis Abreve -50\n"+
    "KPX Ydieresis Acircumflex -50\n"+
    "KPX Ydieresis Adieresis -50\n"+
    "KPX Ydieresis Agrave -50\n"+
    "KPX Ydieresis Amacron -50\n"+
    "KPX Ydieresis Aogonek -50\n"+
    "KPX Ydieresis Aring -50\n"+
    "KPX Ydieresis Atilde -50\n"+
    "KPX Ydieresis O -15\n"+
    "KPX Ydieresis Oacute -15\n"+
    "KPX Ydieresis Ocircumflex -15\n"+
    "KPX Ydieresis Odieresis -15\n"+
    "KPX Ydieresis Ograve -15\n"+
    "KPX Ydieresis Ohungarumlaut -15\n"+
    "KPX Ydieresis Omacron -15\n"+
    "KPX Ydieresis Oslash -15\n"+
    "KPX Ydieresis Otilde -15\n"+
    "KPX Ydieresis a -92\n"+
    "KPX Ydieresis aacute -92\n"+
    "KPX Ydieresis abreve -92\n"+
    "KPX Ydieresis acircumflex -92\n"+
    "KPX Ydieresis adieresis -92\n"+
    "KPX Ydieresis agrave -92\n"+
    "KPX Ydieresis amacron -92\n"+
    "KPX Ydieresis aogonek -92\n"+
    "KPX Ydieresis aring -92\n"+
    "KPX Ydieresis atilde -92\n"+
    "KPX Ydieresis colon -65\n"+
    "KPX Ydieresis comma -92\n"+
    "KPX Ydieresis e -92\n"+
    "KPX Ydieresis eacute -92\n"+
    "KPX Ydieresis ecaron -92\n"+
    "KPX Ydieresis ecircumflex -92\n"+
    "KPX Ydieresis edieresis -52\n"+
    "KPX Ydieresis edotaccent -92\n"+
    "KPX Ydieresis egrave -52\n"+
    "KPX Ydieresis emacron -52\n"+
    "KPX Ydieresis eogonek -92\n"+
    "KPX Ydieresis hyphen -74\n"+
    "KPX Ydieresis i -74\n"+
    "KPX Ydieresis iacute -74\n"+
    "KPX Ydieresis icircumflex -34\n"+
    "KPX Ydieresis idieresis -34\n"+
    "KPX Ydieresis igrave -34\n"+
    "KPX Ydieresis imacron -34\n"+
    "KPX Ydieresis iogonek -74\n"+
    "KPX Ydieresis o -92\n"+
    "KPX Ydieresis oacute -92\n"+
    "KPX Ydieresis ocircumflex -92\n"+
    "KPX Ydieresis odieresis -92\n"+
    "KPX Ydieresis ograve -92\n"+
    "KPX Ydieresis ohungarumlaut -92\n"+
    "KPX Ydieresis omacron -92\n"+
    "KPX Ydieresis oslash -92\n"+
    "KPX Ydieresis otilde -92\n"+
    "KPX Ydieresis period -92\n"+
    "KPX Ydieresis semicolon -65\n"+
    "KPX Ydieresis u -92\n"+
    "KPX Ydieresis uacute -92\n"+
    "KPX Ydieresis ucircumflex -92\n"+
    "KPX Ydieresis udieresis -92\n"+
    "KPX Ydieresis ugrave -92\n"+
    "KPX Ydieresis uhungarumlaut -92\n"+
    "KPX Ydieresis umacron -92\n"+
    "KPX Ydieresis uogonek -92\n"+
    "KPX Ydieresis uring -92\n"+
    "KPX a g -10\n"+
    "KPX a gbreve -10\n"+
    "KPX a gcommaaccent -10\n"+
    "KPX aacute g -10\n"+
    "KPX aacute gbreve -10\n"+
    "KPX aacute gcommaaccent -10\n"+
    "KPX abreve g -10\n"+
    "KPX abreve gbreve -10\n"+
    "KPX abreve gcommaaccent -10\n"+
    "KPX acircumflex g -10\n"+
    "KPX acircumflex gbreve -10\n"+
    "KPX acircumflex gcommaaccent -10\n"+
    "KPX adieresis g -10\n"+
    "KPX adieresis gbreve -10\n"+
    "KPX adieresis gcommaaccent -10\n"+
    "KPX agrave g -10\n"+
    "KPX agrave gbreve -10\n"+
    "KPX agrave gcommaaccent -10\n"+
    "KPX amacron g -10\n"+
    "KPX amacron gbreve -10\n"+
    "KPX amacron gcommaaccent -10\n"+
    "KPX aogonek g -10\n"+
    "KPX aogonek gbreve -10\n"+
    "KPX aogonek gcommaaccent -10\n"+
    "KPX aring g -10\n"+
    "KPX aring gbreve -10\n"+
    "KPX aring gcommaaccent -10\n"+
    "KPX atilde g -10\n"+
    "KPX atilde gbreve -10\n"+
    "KPX atilde gcommaaccent -10\n"+
    "KPX b period -40\n"+
    "KPX b u -20\n"+
    "KPX b uacute -20\n"+
    "KPX b ucircumflex -20\n"+
    "KPX b udieresis -20\n"+
    "KPX b ugrave -20\n"+
    "KPX b uhungarumlaut -20\n"+
    "KPX b umacron -20\n"+
    "KPX b uogonek -20\n"+
    "KPX b uring -20\n"+
    "KPX c h -15\n"+
    "KPX c k -20\n"+
    "KPX c kcommaaccent -20\n"+
    "KPX cacute h -15\n"+
    "KPX cacute k -20\n"+
    "KPX cacute kcommaaccent -20\n"+
    "KPX ccaron h -15\n"+
    "KPX ccaron k -20\n"+
    "KPX ccaron kcommaaccent -20\n"+
    "KPX ccedilla h -15\n"+
    "KPX ccedilla k -20\n"+
    "KPX ccedilla kcommaaccent -20\n"+
    "KPX comma quotedblright -140\n"+
    "KPX comma quoteright -140\n"+
    "KPX e comma -10\n"+
    "KPX e g -40\n"+
    "KPX e gbreve -40\n"+
    "KPX e gcommaaccent -40\n"+
    "KPX e period -15\n"+
    "KPX e v -15\n"+
    "KPX e w -15\n"+
    "KPX e x -20\n"+
    "KPX e y -30\n"+
    "KPX e yacute -30\n"+
    "KPX e ydieresis -30\n"+
    "KPX eacute comma -10\n"+
    "KPX eacute g -40\n"+
    "KPX eacute gbreve -40\n"+
    "KPX eacute gcommaaccent -40\n"+
    "KPX eacute period -15\n"+
    "KPX eacute v -15\n"+
    "KPX eacute w -15\n"+
    "KPX eacute x -20\n"+
    "KPX eacute y -30\n"+
    "KPX eacute yacute -30\n"+
    "KPX eacute ydieresis -30\n"+
    "KPX ecaron comma -10\n"+
    "KPX ecaron g -40\n"+
    "KPX ecaron gbreve -40\n"+
    "KPX ecaron gcommaaccent -40\n"+
    "KPX ecaron period -15\n"+
    "KPX ecaron v -15\n"+
    "KPX ecaron w -15\n"+
    "KPX ecaron x -20\n"+
    "KPX ecaron y -30\n"+
    "KPX ecaron yacute -30\n"+
    "KPX ecaron ydieresis -30\n"+
    "KPX ecircumflex comma -10\n"+
    "KPX ecircumflex g -40\n"+
    "KPX ecircumflex gbreve -40\n"+
    "KPX ecircumflex gcommaaccent -40\n"+
    "KPX ecircumflex period -15\n"+
    "KPX ecircumflex v -15\n"+
    "KPX ecircumflex w -15\n"+
    "KPX ecircumflex x -20\n"+
    "KPX ecircumflex y -30\n"+
    "KPX ecircumflex yacute -30\n"+
    "KPX ecircumflex ydieresis -30\n"+
    "KPX edieresis comma -10\n"+
    "KPX edieresis g -40\n"+
    "KPX edieresis gbreve -40\n"+
    "KPX edieresis gcommaaccent -40\n"+
    "KPX edieresis period -15\n"+
    "KPX edieresis v -15\n"+
    "KPX edieresis w -15\n"+
    "KPX edieresis x -20\n"+
    "KPX edieresis y -30\n"+
    "KPX edieresis yacute -30\n"+
    "KPX edieresis ydieresis -30\n"+
    "KPX edotaccent comma -10\n"+
    "KPX edotaccent g -40\n"+
    "KPX edotaccent gbreve -40\n"+
    "KPX edotaccent gcommaaccent -40\n"+
    "KPX edotaccent period -15\n"+
    "KPX edotaccent v -15\n"+
    "KPX edotaccent w -15\n"+
    "KPX edotaccent x -20\n"+
    "KPX edotaccent y -30\n"+
    "KPX edotaccent yacute -30\n"+
    "KPX edotaccent ydieresis -30\n"+
    "KPX egrave comma -10\n"+
    "KPX egrave g -40\n"+
    "KPX egrave gbreve -40\n"+
    "KPX egrave gcommaaccent -40\n"+
    "KPX egrave period -15\n"+
    "KPX egrave v -15\n"+
    "KPX egrave w -15\n"+
    "KPX egrave x -20\n"+
    "KPX egrave y -30\n"+
    "KPX egrave yacute -30\n"+
    "KPX egrave ydieresis -30\n"+
    "KPX emacron comma -10\n"+
    "KPX emacron g -40\n"+
    "KPX emacron gbreve -40\n"+
    "KPX emacron gcommaaccent -40\n"+
    "KPX emacron period -15\n"+
    "KPX emacron v -15\n"+
    "KPX emacron w -15\n"+
    "KPX emacron x -20\n"+
    "KPX emacron y -30\n"+
    "KPX emacron yacute -30\n"+
    "KPX emacron ydieresis -30\n"+
    "KPX eogonek comma -10\n"+
    "KPX eogonek g -40\n"+
    "KPX eogonek gbreve -40\n"+
    "KPX eogonek gcommaaccent -40\n"+
    "KPX eogonek period -15\n"+
    "KPX eogonek v -15\n"+
    "KPX eogonek w -15\n"+
    "KPX eogonek x -20\n"+
    "KPX eogonek y -30\n"+
    "KPX eogonek yacute -30\n"+
    "KPX eogonek ydieresis -30\n"+
    "KPX f comma -10\n"+
    "KPX f dotlessi -60\n"+
    "KPX f f -18\n"+
    "KPX f i -20\n"+
    "KPX f iogonek -20\n"+
    "KPX f period -15\n"+
    "KPX f quoteright 92\n"+
    "KPX g comma -10\n"+
    "KPX g e -10\n"+
    "KPX g eacute -10\n"+
    "KPX g ecaron -10\n"+
    "KPX g ecircumflex -10\n"+
    "KPX g edieresis -10\n"+
    "KPX g edotaccent -10\n"+
    "KPX g egrave -10\n"+
    "KPX g emacron -10\n"+
    "KPX g eogonek -10\n"+
    "KPX g g -10\n"+
    "KPX g gbreve -10\n"+
    "KPX g gcommaaccent -10\n"+
    "KPX g period -15\n"+
    "KPX gbreve comma -10\n"+
    "KPX gbreve e -10\n"+
    "KPX gbreve eacute -10\n"+
    "KPX gbreve ecaron -10\n"+
    "KPX gbreve ecircumflex -10\n"+
    "KPX gbreve edieresis -10\n"+
    "KPX gbreve edotaccent -10\n"+
    "KPX gbreve egrave -10\n"+
    "KPX gbreve emacron -10\n"+
    "KPX gbreve eogonek -10\n"+
    "KPX gbreve g -10\n"+
    "KPX gbreve gbreve -10\n"+
    "KPX gbreve gcommaaccent -10\n"+
    "KPX gbreve period -15\n"+
    "KPX gcommaaccent comma -10\n"+
    "KPX gcommaaccent e -10\n"+
    "KPX gcommaaccent eacute -10\n"+
    "KPX gcommaaccent ecaron -10\n"+
    "KPX gcommaaccent ecircumflex -10\n"+
    "KPX gcommaaccent edieresis -10\n"+
    "KPX gcommaaccent edotaccent -10\n"+
    "KPX gcommaaccent egrave -10\n"+
    "KPX gcommaaccent emacron -10\n"+
    "KPX gcommaaccent eogonek -10\n"+
    "KPX gcommaaccent g -10\n"+
    "KPX gcommaaccent gbreve -10\n"+
    "KPX gcommaaccent gcommaaccent -10\n"+
    "KPX gcommaaccent period -15\n"+
    "KPX k e -10\n"+
    "KPX k eacute -10\n"+
    "KPX k ecaron -10\n"+
    "KPX k ecircumflex -10\n"+
    "KPX k edieresis -10\n"+
    "KPX k edotaccent -10\n"+
    "KPX k egrave -10\n"+
    "KPX k emacron -10\n"+
    "KPX k eogonek -10\n"+
    "KPX k o -10\n"+
    "KPX k oacute -10\n"+
    "KPX k ocircumflex -10\n"+
    "KPX k odieresis -10\n"+
    "KPX k ograve -10\n"+
    "KPX k ohungarumlaut -10\n"+
    "KPX k omacron -10\n"+
    "KPX k oslash -10\n"+
    "KPX k otilde -10\n"+
    "KPX k y -10\n"+
    "KPX k yacute -10\n"+
    "KPX k ydieresis -10\n"+
    "KPX kcommaaccent e -10\n"+
    "KPX kcommaaccent eacute -10\n"+
    "KPX kcommaaccent ecaron -10\n"+
    "KPX kcommaaccent ecircumflex -10\n"+
    "KPX kcommaaccent edieresis -10\n"+
    "KPX kcommaaccent edotaccent -10\n"+
    "KPX kcommaaccent egrave -10\n"+
    "KPX kcommaaccent emacron -10\n"+
    "KPX kcommaaccent eogonek -10\n"+
    "KPX kcommaaccent o -10\n"+
    "KPX kcommaaccent oacute -10\n"+
    "KPX kcommaaccent ocircumflex -10\n"+
    "KPX kcommaaccent odieresis -10\n"+
    "KPX kcommaaccent ograve -10\n"+
    "KPX kcommaaccent ohungarumlaut -10\n"+
    "KPX kcommaaccent omacron -10\n"+
    "KPX kcommaaccent oslash -10\n"+
    "KPX kcommaaccent otilde -10\n"+
    "KPX kcommaaccent y -10\n"+
    "KPX kcommaaccent yacute -10\n"+
    "KPX kcommaaccent ydieresis -10\n"+
    "KPX n v -40\n"+
    "KPX nacute v -40\n"+
    "KPX ncaron v -40\n"+
    "KPX ncommaaccent v -40\n"+
    "KPX ntilde v -40\n"+
    "KPX o g -10\n"+
    "KPX o gbreve -10\n"+
    "KPX o gcommaaccent -10\n"+
    "KPX o v -10\n"+
    "KPX oacute g -10\n"+
    "KPX oacute gbreve -10\n"+
    "KPX oacute gcommaaccent -10\n"+
    "KPX oacute v -10\n"+
    "KPX ocircumflex g -10\n"+
    "KPX ocircumflex gbreve -10\n"+
    "KPX ocircumflex gcommaaccent -10\n"+
    "KPX ocircumflex v -10\n"+
    "KPX odieresis g -10\n"+
    "KPX odieresis gbreve -10\n"+
    "KPX odieresis gcommaaccent -10\n"+
    "KPX odieresis v -10\n"+
    "KPX ograve g -10\n"+
    "KPX ograve gbreve -10\n"+
    "KPX ograve gcommaaccent -10\n"+
    "KPX ograve v -10\n"+
    "KPX ohungarumlaut g -10\n"+
    "KPX ohungarumlaut gbreve -10\n"+
    "KPX ohungarumlaut gcommaaccent -10\n"+
    "KPX ohungarumlaut v -10\n"+
    "KPX omacron g -10\n"+
    "KPX omacron gbreve -10\n"+
    "KPX omacron gcommaaccent -10\n"+
    "KPX omacron v -10\n"+
    "KPX oslash g -10\n"+
    "KPX oslash gbreve -10\n"+
    "KPX oslash gcommaaccent -10\n"+
    "KPX oslash v -10\n"+
    "KPX otilde g -10\n"+
    "KPX otilde gbreve -10\n"+
    "KPX otilde gcommaaccent -10\n"+
    "KPX otilde v -10\n"+
    "KPX period quotedblright -140\n"+
    "KPX period quoteright -140\n"+
    "KPX quoteleft quoteleft -111\n"+
    "KPX quoteright d -25\n"+
    "KPX quoteright dcroat -25\n"+
    "KPX quoteright quoteright -111\n"+
    "KPX quoteright r -25\n"+
    "KPX quoteright racute -25\n"+
    "KPX quoteright rcaron -25\n"+
    "KPX quoteright rcommaaccent -25\n"+
    "KPX quoteright s -40\n"+
    "KPX quoteright sacute -40\n"+
    "KPX quoteright scaron -40\n"+
    "KPX quoteright scedilla -40\n"+
    "KPX quoteright scommaaccent -40\n"+
    "KPX quoteright space -111\n"+
    "KPX quoteright t -30\n"+
    "KPX quoteright tcommaaccent -30\n"+
    "KPX quoteright v -10\n"+
    "KPX r a -15\n"+
    "KPX r aacute -15\n"+
    "KPX r abreve -15\n"+
    "KPX r acircumflex -15\n"+
    "KPX r adieresis -15\n"+
    "KPX r agrave -15\n"+
    "KPX r amacron -15\n"+
    "KPX r aogonek -15\n"+
    "KPX r aring -15\n"+
    "KPX r atilde -15\n"+
    "KPX r c -37\n"+
    "KPX r cacute -37\n"+
    "KPX r ccaron -37\n"+
    "KPX r ccedilla -37\n"+
    "KPX r comma -111\n"+
    "KPX r d -37\n"+
    "KPX r dcroat -37\n"+
    "KPX r e -37\n"+
    "KPX r eacute -37\n"+
    "KPX r ecaron -37\n"+
    "KPX r ecircumflex -37\n"+
    "KPX r edieresis -37\n"+
    "KPX r edotaccent -37\n"+
    "KPX r egrave -37\n"+
    "KPX r emacron -37\n"+
    "KPX r eogonek -37\n"+
    "KPX r g -37\n"+
    "KPX r gbreve -37\n"+
    "KPX r gcommaaccent -37\n"+
    "KPX r hyphen -20\n"+
    "KPX r o -45\n"+
    "KPX r oacute -45\n"+
    "KPX r ocircumflex -45\n"+
    "KPX r odieresis -45\n"+
    "KPX r ograve -45\n"+
    "KPX r ohungarumlaut -45\n"+
    "KPX r omacron -45\n"+
    "KPX r oslash -45\n"+
    "KPX r otilde -45\n"+
    "KPX r period -111\n"+
    "KPX r q -37\n"+
    "KPX r s -10\n"+
    "KPX r sacute -10\n"+
    "KPX r scaron -10\n"+
    "KPX r scedilla -10\n"+
    "KPX r scommaaccent -10\n"+
    "KPX racute a -15\n"+
    "KPX racute aacute -15\n"+
    "KPX racute abreve -15\n"+
    "KPX racute acircumflex -15\n"+
    "KPX racute adieresis -15\n"+
    "KPX racute agrave -15\n"+
    "KPX racute amacron -15\n"+
    "KPX racute aogonek -15\n"+
    "KPX racute aring -15\n"+
    "KPX racute atilde -15\n"+
    "KPX racute c -37\n"+
    "KPX racute cacute -37\n"+
    "KPX racute ccaron -37\n"+
    "KPX racute ccedilla -37\n"+
    "KPX racute comma -111\n"+
    "KPX racute d -37\n"+
    "KPX racute dcroat -37\n"+
    "KPX racute e -37\n"+
    "KPX racute eacute -37\n"+
    "KPX racute ecaron -37\n"+
    "KPX racute ecircumflex -37\n"+
    "KPX racute edieresis -37\n"+
    "KPX racute edotaccent -37\n"+
    "KPX racute egrave -37\n"+
    "KPX racute emacron -37\n"+
    "KPX racute eogonek -37\n"+
    "KPX racute g -37\n"+
    "KPX racute gbreve -37\n"+
    "KPX racute gcommaaccent -37\n"+
    "KPX racute hyphen -20\n"+
    "KPX racute o -45\n"+
    "KPX racute oacute -45\n"+
    "KPX racute ocircumflex -45\n"+
    "KPX racute odieresis -45\n"+
    "KPX racute ograve -45\n"+
    "KPX racute ohungarumlaut -45\n"+
    "KPX racute omacron -45\n"+
    "KPX racute oslash -45\n"+
    "KPX racute otilde -45\n"+
    "KPX racute period -111\n"+
    "KPX racute q -37\n"+
    "KPX racute s -10\n"+
    "KPX racute sacute -10\n"+
    "KPX racute scaron -10\n"+
    "KPX racute scedilla -10\n"+
    "KPX racute scommaaccent -10\n"+
    "KPX rcaron a -15\n"+
    "KPX rcaron aacute -15\n"+
    "KPX rcaron abreve -15\n"+
    "KPX rcaron acircumflex -15\n"+
    "KPX rcaron adieresis -15\n"+
    "KPX rcaron agrave -15\n"+
    "KPX rcaron amacron -15\n"+
    "KPX rcaron aogonek -15\n"+
    "KPX rcaron aring -15\n"+
    "KPX rcaron atilde -15\n"+
    "KPX rcaron c -37\n"+
    "KPX rcaron cacute -37\n"+
    "KPX rcaron ccaron -37\n"+
    "KPX rcaron ccedilla -37\n"+
    "KPX rcaron comma -111\n"+
    "KPX rcaron d -37\n"+
    "KPX rcaron dcroat -37\n"+
    "KPX rcaron e -37\n"+
    "KPX rcaron eacute -37\n"+
    "KPX rcaron ecaron -37\n"+
    "KPX rcaron ecircumflex -37\n"+
    "KPX rcaron edieresis -37\n"+
    "KPX rcaron edotaccent -37\n"+
    "KPX rcaron egrave -37\n"+
    "KPX rcaron emacron -37\n"+
    "KPX rcaron eogonek -37\n"+
    "KPX rcaron g -37\n"+
    "KPX rcaron gbreve -37\n"+
    "KPX rcaron gcommaaccent -37\n"+
    "KPX rcaron hyphen -20\n"+
    "KPX rcaron o -45\n"+
    "KPX rcaron oacute -45\n"+
    "KPX rcaron ocircumflex -45\n"+
    "KPX rcaron odieresis -45\n"+
    "KPX rcaron ograve -45\n"+
    "KPX rcaron ohungarumlaut -45\n"+
    "KPX rcaron omacron -45\n"+
    "KPX rcaron oslash -45\n"+
    "KPX rcaron otilde -45\n"+
    "KPX rcaron period -111\n"+
    "KPX rcaron q -37\n"+
    "KPX rcaron s -10\n"+
    "KPX rcaron sacute -10\n"+
    "KPX rcaron scaron -10\n"+
    "KPX rcaron scedilla -10\n"+
    "KPX rcaron scommaaccent -10\n"+
    "KPX rcommaaccent a -15\n"+
    "KPX rcommaaccent aacute -15\n"+
    "KPX rcommaaccent abreve -15\n"+
    "KPX rcommaaccent acircumflex -15\n"+
    "KPX rcommaaccent adieresis -15\n"+
    "KPX rcommaaccent agrave -15\n"+
    "KPX rcommaaccent amacron -15\n"+
    "KPX rcommaaccent aogonek -15\n"+
    "KPX rcommaaccent aring -15\n"+
    "KPX rcommaaccent atilde -15\n"+
    "KPX rcommaaccent c -37\n"+
    "KPX rcommaaccent cacute -37\n"+
    "KPX rcommaaccent ccaron -37\n"+
    "KPX rcommaaccent ccedilla -37\n"+
    "KPX rcommaaccent comma -111\n"+
    "KPX rcommaaccent d -37\n"+
    "KPX rcommaaccent dcroat -37\n"+
    "KPX rcommaaccent e -37\n"+
    "KPX rcommaaccent eacute -37\n"+
    "KPX rcommaaccent ecaron -37\n"+
    "KPX rcommaaccent ecircumflex -37\n"+
    "KPX rcommaaccent edieresis -37\n"+
    "KPX rcommaaccent edotaccent -37\n"+
    "KPX rcommaaccent egrave -37\n"+
    "KPX rcommaaccent emacron -37\n"+
    "KPX rcommaaccent eogonek -37\n"+
    "KPX rcommaaccent g -37\n"+
    "KPX rcommaaccent gbreve -37\n"+
    "KPX rcommaaccent gcommaaccent -37\n"+
    "KPX rcommaaccent hyphen -20\n"+
    "KPX rcommaaccent o -45\n"+
    "KPX rcommaaccent oacute -45\n"+
    "KPX rcommaaccent ocircumflex -45\n"+
    "KPX rcommaaccent odieresis -45\n"+
    "KPX rcommaaccent ograve -45\n"+
    "KPX rcommaaccent ohungarumlaut -45\n"+
    "KPX rcommaaccent omacron -45\n"+
    "KPX rcommaaccent oslash -45\n"+
    "KPX rcommaaccent otilde -45\n"+
    "KPX rcommaaccent period -111\n"+
    "KPX rcommaaccent q -37\n"+
    "KPX rcommaaccent s -10\n"+
    "KPX rcommaaccent sacute -10\n"+
    "KPX rcommaaccent scaron -10\n"+
    "KPX rcommaaccent scedilla -10\n"+
    "KPX rcommaaccent scommaaccent -10\n"+
    "KPX space A -18\n"+
    "KPX space Aacute -18\n"+
    "KPX space Abreve -18\n"+
    "KPX space Acircumflex -18\n"+
    "KPX space Adieresis -18\n"+
    "KPX space Agrave -18\n"+
    "KPX space Amacron -18\n"+
    "KPX space Aogonek -18\n"+
    "KPX space Aring -18\n"+
    "KPX space Atilde -18\n"+
    "KPX space T -18\n"+
    "KPX space Tcaron -18\n"+
    "KPX space Tcommaaccent -18\n"+
    "KPX space V -35\n"+
    "KPX space W -40\n"+
    "KPX space Y -75\n"+
    "KPX space Yacute -75\n"+
    "KPX space Ydieresis -75\n"+
    "KPX v comma -74\n"+
    "KPX v period -74\n"+
    "KPX w comma -74\n"+
    "KPX w period -74\n"+
    "KPX y comma -55\n"+
    "KPX y period -55\n"+
    "KPX yacute comma -55\n"+
    "KPX yacute period -55\n"+
    "KPX ydieresis comma -55\n"+
    "KPX ydieresis period -55\n"+
    "EndKernPairs\n"+
    "EndKernData\n"+
    "EndFontMetrics\n";
}

